.settings/org.eclipse.buildship.core.prefs, .settings/org.eclipse.jdt.core.prefs, src/main/java/tetris/AbstractShape.java, src/main/java/tetris/Grid.java, src/main/java/tetris/View.java
* The color of the tetromino is randomly picked at tetromino generation.
* There are 6 color options, each more fugly than the other
=> Added coloring options

src/main/java/tetris/AbstractShape.java
Blocks that make up a Tetromino are called Minos.
=> Javadoc abstractshape

src/main/java/tetris/AbstractShape.java, src/main/java/tetris/Controller.java, src/main/java/tetris/Coordinate.java, src/main/java/tetris/Grid.java, src/main/java/tetris/ShapeI.java, src/main/java/tetris/ShapeJ.java, src/main/java/tetris/ShapeL.java, src/main/java/tetris/ShapeO.java, src/main/java/tetris/ShapeS.java, src/main/java/tetris/ShapeT.java, src/main/java/tetris/ShapeZ.java, src/main/java/tetris/TetrominoFactory.java, src/main/java/tetris/View.java, src/test/java/tetris/AbstractShapeTest.java, src/test/java/tetris/DummyShape.java
Extracted all arrays of integers representing a coordinate to a Coordinate object.
=> Extract coordinate to own class

src/main/java/tetris/AbstractShape.java, src/main/java/tetris/Controller.java
Updated Pascals code with another PR
=> update nav new Coordinate class

feedback/week-3.md
Please look it over, if you have any comments we can discuss this tomorrow.
=> Feedback week 3

src/main/java/tetris/Controller.java, src/main/java/tetris/KeyBindings.java
Different key bindings and softdrop
=> Soft drop implemented

src/main/java/tetris/Controller.java, src/main/java/tetris/Score.java, src/main/java/tetris/scenes/GameScreen.java, src/main/java/tetris/scenes/ObservingLabel.java
I extracted the private classes to increase the extensibility of our code.
=> Extract private classes

src/main/java/tetris/Controller.java, src/main/java/tetris/TetrominoMovementHandler.java
moved the tetromino motion responsibilities to a separate class
=> Making controller less complex

src/main/java/logging/Logger.java, src/main/java/tetris/Coordinate.java, src/main/java/tetris/KeyBindings.java, src/main/java/tetris/Score.java, src/main/java/tetris/Settings.java, src/main/java/tetris/TetrominoMovementHandler.java, src/main/java/tetris/Tick.java, src/main/java/tetris/View.java, src/main/java/tetris/scenes/GameScreen.java, src/main/java/tetris/scenes/MainScreen.java, src/main/java/tetris/scenes/ObservingLabel.java, src/main/java/tetris/scenes/SettingsScreen.java, src/main/java/tetris/tetromino/TetrominoFactory.java, src/main/java/tetris/tetromino/TetrominoQueue.java, src/main/java/tetris/tetromino/TetrominoType.java, src/test/java/logging/LoggerTest.java, src/test/java/tetris/AllTests.java, src/test/java/tetris/GridTest.java, src/test/java/tetris/KeyBindingsTest.java, src/test/java/tetris/LoggerTest.java, src/test/java/tetris/ScoreTest.java, src/test/java/tetris/TetrominoMovementHandlerTest.java, src/test/java/tetris/TetrominoTest.java
general code improvements. contains a buttload of changes to docstrings and variable names so if this lies around it will definately source a lot of merge conflicts on your own branches ;)
=> Additional testing

src/main/java/tetris/Controller.java, src/main/java/tetris/View.java, src/main/java/tetris/scenes/PromptNameScreen.java, src/test/java/tetris/LoggerTest.java
- Adds a prompt for the player's name when the player is game over
*Note*
The prompt will always be shown at the end of a game. Some logic should be added to the game to check when a player sets a highscore so that the prompt only opens when there is a new highscore set.
=> Working prompt for playername to register highscore

src/main/java/tetris/Controller.java, src/main/java/tetris/KeyBindings.java, src/main/java/tetris/scenes/SettingsScreen.java, src/test/java/tetris/KeyBindingsTest.java
This fixes the key bindings settings menu. There was some misconception about the key of a HashMap and the key of an keyboard.
This also handles unset key bindings while playing the game.
=> Fix for setting key bindings and handling unset key bindings

src/test/java/tetris/DummyShapeI.java, src/test/java/tetris/DummyShapeO.java, src/test/java/tetris/TetrominoMovementHandlerTest.java
- Use dummy shapes for testing instead of shapes implemented in the game
=> Fixes for movement handler tests

src/test/java/tetris/DummyShape.java, src/test/java/tetris/GridTest.java
- Splits test into different cases
- Use dummy shape for testing (maybe mocking is better?)
=> Split test into different cases and use a dummy shape for testing

src/main/java/tetris/scenes/PreviewAdapter.java
- Some fields don't need to be class fields because they are just local variables
- Update JavaDoc
- Shorten code where possible
=> Code improvements for PreviewAdapter

src/main/java/tetris/TetrominoMovementHandler.java
- Refactor code to avoid unnecessary return statement
=> Resolves control flow issue

config/checkstyle/checkstyle.xml, src/main/java/highscore/GameEntry.java, src/main/java/highscore/ScoreBoard.java, src/main/java/tetris/Controller.java, src/main/java/tetris/Settings.java, src/main/java/tetris/View.java, src/main/java/tetris/scenes/HighscoreScreen.java, src/main/java/tetris/scenes/IScreen.java, src/main/java/tetris/scenes/PreviewAdapter.java, src/main/java/tetris/scenes/PromptNameScreen.java, src/main/java/tetris/scenes/SettingsScreen.java, src/test/java/tetris/PreviewAdapterTest.java
- Added 'e' to the list of allowed single character variable names
=> Resolves all current CheckStyle warns

src/main/java/tetris/Controller.java, src/main/java/tetris/scenes/GameScreen.java
sorry for the other PR, it was a mistake.
=> PauseButton in the working Branch(without Gameover bug)

src/main/java/tetris/Action.java, src/main/java/tetris/Controller.java, src/main/java/tetris/KeyBindings.java, src/main/java/tetris/Settings.java, src/main/java/tetris/scenes/SettingsScreen.java, src/test/java/tetris/KeyBindingsTest.java
Usage of Enum instead of strings for the different actions, way more chique and allows things like fancy names and other overrides in the future.
=> Action enum

src/main/java/tetris/Action.java, src/main/java/tetris/tetromino/AbstractTetromino.java, src/test/java/tetris/ActionTest.java
Sebas said it might not be the cleanest method, maybe not, but it works. Could the rest take a look a it?
=> Kick flip turn

src/main/java/tetris/KeyBindings.java, src/test/java/tetris/KeyBindingsTest.java
New equals function for the keyBindings + tests
=> KeyBindings equals function and tests

src/test/java/tetris/KarelGitHubTest.java
=> github test

src/main/java/tetris/Controller.java, src/main/java/tetris/Grid.java, src/main/java/tetris/TetrominoQueue.java, src/main/java/tetris/shapes/IFactory.java, src/main/java/tetris/shapes/ShapeType.java, src/main/java/tetris/shapes/custom/TrominoFactory.java, src/main/java/tetris/shapes/custom/TrominoI.java, src/main/java/tetris/shapes/custom/TrominoJ.java, src/main/java/tetris/shapes/custom/TrominoL.java, src/main/java/tetris/shapes/custom/TrominoType.java, src/main/java/tetris/shapes/original/TetrominoFactory.java, src/main/java/tetris/shapes/original/TetrominoType.java, src/test/java/tetris/DummyController.java, src/test/java/tetris/GridTest.java, src/test/java/tetris/PreviewAdapterTest.java, src/test/java/tetris/TetrominoFactoryTest.java
Applying the Open/Closed principle to the creation of shapes. This demonstrates how a new set of shapes can be added to the game.
=> Demo of adding new shape set to the game

src/main/java/tetris/Grid.java, src/main/java/tetris/scenes/GridCanvas.java
Adds a shape shadow so the player knowns where the tetromino will land if it is not moved.
=> Hard drop preview for falling tetromino

src/main/java/tetris/Controller.java, src/main/java/tetris/Score.java, src/main/java/tetris/scenes/GameScreen.java, src/test/java/tetris/ScoreTest.java
1 level per line
removed scoretest, was annoying
=> Level grid
